services:
  app:
    build: .
    container_name: app
    command: ["npm", "start"]
    restart: unless-stopped
    ports:
      - "8967:8967"
    env_file:
      - .env.prod
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  worker:
    build: .
    container_name: worker
    command: ["npm", "run", "worker"]
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
